### ISSUE TITLE
Log output confusing when multiple happy-eyeballs instances in play

### ISSUE THREAD

**Issue by reynir** [robur-coop/happy-eyeballs#35]
When using `Happy_eyeballs_lwt` two instances of happy-eyeballs are active: one in `Happy_eyeballs_lwt` and one in `Dns_client_lwt`. This leads to log messages where it is not possible to tell which instance it originates from. See https://github.com/ocaml/infrastructure/issues/73#issuecomment-1726736692 for an example.

I'm not sure what to do about it, and I can't think of an elegant solution; maybe this is a WONTFIX.

**Comment by hannesm** [comment]
What we can do, is use a mutable reference, which we store within `create` in the record and increment it.This way, each `create` will return a fresh counter, which we can use in log output. WDYT?

**Comment by reynir** [comment]
Thanks!
